version: "3.0"
services:
  db:
  image: mysql:5.7.19
  environment:
    - MYSQL_DATABASE=loja
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes:
    - /home/desenvolvimento1/Documents/Kurbenetes/Curso-Kurbenetes-Alura/volume:/var/lib/mysql